---
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: 10
production:
  :concurrency: 6
  :timeout: 30
:queues:
  - [sunspot, 7]
  - [default, 5]
  - [mass_upload_prioritized, 4]
  - [mass_upload, 3]